import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./app.scss"
import Nav from "@/components/navigation/nav";
import {TelegramProvider} from "@/app/useTg";
import Script from "next/script";
import {Toaster} from "react-hot-toast";

const poppins = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"], display: 'swap', style: 'normal' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
      />
      <div>
          <TelegramProvider>
              <main>
                  {children}
              </main>
              <footer>
                  <Nav/>
              </footer>
              <Toaster position="bottom-center" reverseOrder={true} toastOptions={{duration: 2500}}/>
          </TelegramProvider>
      </div>
      </body>
    </html>
  );
}
