# Generated by Django 4.2.7 on 2023-11-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_davdamer"),
        ("partner", "0006_auto_20200724_0909"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("partner.partner",),
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Продавец", "verbose_name_plural": "Продавцы"},
        ),
        migrations.AddField(
            model_name="partner",
            name="davdamer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sellers",
                to="core.davdamer",
            ),
            preserve_default=False,
        ),
    ]
