# Generated by Django 4.2.7 on 2023-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0007_seller_alter_partner_options_partner_davdamer"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/sellers"),
        ),
    ]
