# Generated by Django 4.2.7 on 2023-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0008_partner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
