# Generated by Django 4.2.7 on 2023-12-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0009_partner_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
