# Generated by Django 4.2.7 on 2023-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0010_partner_address_partner_description_partner_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="registered_dt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="updated_dt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
