# Generated by Django 4.2.7 on 2023-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0011_partner_registered_dt_partner_updated_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="country",
            field=models.CharField(
                blank=True, default="Россия", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="market",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
