# Generated by Django 4.2.7 on 2024-01-11 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0012_partner_city_partner_country_partner_market"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="city",
        ),
    ]
