# Generated by Django 4.2.10 on 2024-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0015_partner_enot_secret_key_partner_enot_shop_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="measurement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Единица измерения"
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Старая цена",
            ),
        ),
    ]
