// src/app/layout.tsx (без директивы 'use client')
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./app.scss"
import Nav from "@/components/navigation/nav";
import {TelegramProvider} from "@/app/useTg";
import Script from "next/script";
import {Toaster} from "react-hot-toast";
import DisableZoom from './DisableZoom'
import PendingOrderBanner from "@/components/pending-order/pending-order-banner";
import PaymentReminderBanner from "@/components/pending-order/payment-reminder-banner";
import HapticInit from "./HapticInit"; // Новый клиентский компонент

const poppins = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"], display: 'swap', style: 'normal' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body className={poppins.className}>
        <DisableZoom />

        <Script
            src="https://telegram.org/js/telegram-web-app.js"
            strategy="beforeInteractive"
        />
        <div>
            <TelegramProvider>
                <HapticInit /> {/* Клиентский компонент для инициализации вибрации */}
                <main>
                    <PendingOrderBanner />
                    <PaymentReminderBanner />
                    {children}
                </main>
                <footer>
                    <Nav/>
                </footer>
                <Toaster position="bottom-center" reverseOrder={true} toastOptions={{duration: 2500}}/>
            </TelegramProvider>
        </div>
      </body>
    </html>
  );
}