# Generated by Django 4.2.7 on 2023-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_tax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_field",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
