# Generated by Django 4.2.7 on 2023-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_custom_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "Новый"),
                    ("PAID", "Оплачен"),
                    ("PROCESSING", "В обработке"),
                    ("SENT", "Отправлен"),
                    ("DELIVERED", "Доставлен"),
                    ("REFUND", "Возврат"),
                    ("CANCELLED", "Отменён"),
                ],
                max_length=100,
            ),
        ),
    ]
