# Generated by Django 4.2.9 on 2024-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0018_order_updated_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "Новый"),
                    ("PAID", "Оплачен"),
                    ("PROCESSING", "В обработке"),
                    ("READY", "Собран продавцом"),
                    ("SENT", "Отправлен"),
                    ("DELIVERED", "Доставлен"),
                    ("REFUND", "Возврат"),
                    ("CANCELLED", "Отменён"),
                ],
                max_length=100,
            ),
        ),
    ]
