# Generated by Django 4.2.10 on 2024-02-08 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_orderlinediscount"),
        ("order", "0019_alter_order_status"),
    ]

    operations = []
