# Generated by Django 4.2.10 on 2024-02-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0015_partner_enot_secret_key_partner_enot_shop_id_and_more"),
        ("order", "0020_merge_0015_orderlinediscount_0019_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="time",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="partner.partner",
            ),
        ),
    ]
