# Generated by Django 4.2.11 on 2024-03-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0023_line_measurement_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="id заказа после оплаты на Юкассе",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату заказа."
            ),
        ),
    ]
