# Generated by Django 4.2.7 on 2023-11-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0007_seller_alter_partner_options_partner_davdamer"),
        ("catalogue", "0026_predefined_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="partner.seller",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
