# Generated by Django 4.2.7 on 2023-11-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_davdamer"),
        ("catalogue", "0027_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.AddField(
            model_name="product",
            name="davdamer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.davdamer",
            ),
        ),
    ]
