# Generated by Django 4.2.7 on 2023-12-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0009_partner_phone_number"),
        ("catalogue", "0028_remove_product_seller_product_davdamer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="partner.seller",
            ),
        ),
    ]
