# Generated by Django 4.2.9 on 2024-01-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0014_partner_city"),
        ("catalogue", "0029_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="davdamer",
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="partner.seller",
            ),
        ),
    ]
