# Generated by Django 4.2.10 on 2024-02-08 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
        ("catalogue", "0030_remove_product_davdamer_alter_product_seller"),
    ]

    operations = []
