# Generated by Django 4.2.10 on 2024-02-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0031_merge_20240208_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Страна производства",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_dietary",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Диетический"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_gluten_free",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Без глютена"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_sugar_free",
            field=models.BooleanField(blank=True, null=True, verbose_name="Без сахара"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_vegan",
            field=models.BooleanField(blank=True, null=True, verbose_name="Веганский"),
        ),
    ]
