# Generated by Django 4.2.9 on 2024-03-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0032_product_country_product_is_dietary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("NEED_LOGIN", "требуется вход"),
                    ("WITHOUT_LOGIN", "без входа"),
                ],
                default="WITHOUT_LOGIN",
                max_length=20,
            ),
        ),
    ]
