# Generated by Django 4.2.11 on 2024-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0033_product_login_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="login_type",
        ),
        migrations.AddField(
            model_name="product",
            name="login_type",
            field=models.CharField(
                choices=[("EMAIL_CODE", "требуется вход"), ("LINK", "без входа")],
                default="LINK",
                max_length=20,
            ),
        ),
    ]
