# Generated by Django 4.2.11 on 2024-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0034_alter_product_login_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="game",
            field=models.CharField(
                choices=[
                    ("brawl_stars", "Brawl Stars"),
                    ("clash_of_clans", "Clash of Clans"),
                    ("clash_royale", "Clash Royale"),
                    ("hay_day", "Hay Day"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
