# Generated by Django 4.2.7 on 2024-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_davdamer"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
