# Generated by Django 4.2.10 on 2024-02-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_davdamer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="delivery_city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Город доставки"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="delivery_country",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Страна доставки"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receiver_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Имя получателя"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receiver_phone",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Телефон получателя"
            ),
        ),
    ]
