# Generated by Django 4.2.10 on 2024-02-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_user_delivery_address_user_delivery_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ЖК"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="delivery_notes",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Комментарий к доставке",
            ),
        ),
    ]
