# Generated by Django 4.2.11 on 2024-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_delivery_district_user_delivery_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCodeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_successful", models.BooleanField(default=None, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Запрос кода",
                "verbose_name_plural": "Запросы кода",
            },
        ),
    ]
