# Generated by Django 4.2.11 on 2024-03-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_order_payment_id_order_payment_link"),
        ("core", "0008_emailcoderequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLoginData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL игрока"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email для входа",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Код для входа",
                    ),
                ),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_data",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные для входа",
                "verbose_name_plural": "Данные для входа",
                "ordering": ["-created_dt"],
            },
        ),
    ]
