# Generated by Django 4.2.11 on 2024-03-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_order_payment_id_order_payment_link"),
        ("core", "0009_orderlogindata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlogindata",
            name="email",
        ),
        migrations.RemoveField(
            model_name="orderlogindata",
            name="link",
        ),
        migrations.RemoveField(
            model_name="orderlogindata",
            name="order",
        ),
        migrations.AddField(
            model_name="orderlogindata",
            name="account_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="ID аккаунта"
            ),
        ),
        migrations.AddField(
            model_name="orderlogindata",
            name="order_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_data",
                to="order.line",
            ),
        ),
    ]
