# Generated by Django 4.2.11 on 2024-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_orderlogindata_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="brawl_stars_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="clash_of_clans_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="clash_royale_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stumble_guys_email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
