# Generated by Django 4.2.11 on 2024-03-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_user_brawl_stars_email_user_clash_of_clans_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcoderequest",
            name="game",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
